name: flutter_taggable
description: Mention users, insert hashtags, and tag other things with a lightweight and customizable extension to the TextEditingController, and store tags in a database-friendly format.
version: 1.1.3
homepage: https://github.com/WesselvanDam/taggable
repository: https://github.com/WesselvanDam/taggable
issue_tracker: https://github.com/WesselvanDam/taggable/issues

topics: [tag, mention, hashtag, tagging, user]

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: Example of a taggable text field.
    path: doc/flutter_taggable_example_screenshot.png
